# Generated by Django 5.2.3 on 2025-06-20 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='applicant_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='application',
            name='job_duration_days',
            field=models.PositiveIntegerField(blank=True, help_text='Job duration in days for direct hire', null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='next_step_status',
            field=models.CharField(blank=True, choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('DECLINED', 'Declined')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='next_step_type',
            field=models.CharField(blank=True, choices=[('INTERVIEW', 'Interview'), ('DIRECT_HIRE', 'Direct Hire')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='selected_for_next_step',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='job',
            name='next_step',
            field=models.CharField(choices=[('DIRECT_HIRE', 'Direct Hire'), ('INTERVIEW', 'Interview')], default='INTERVIEW', help_text='Next step for applicants: Direct Hire or Interview', max_length=20),
        ),
    ]
