# Generated by Django 5.2.3 on 2025-06-23 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_application_applicant_approved_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='skills',
            field=models.JSONField(blank=True, default=list, help_text='List of skills required for the job'),
        ),
    ]
