# Generated by Django 5.2.3 on 2025-06-24 05:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_jobseekerprofile_linkedin_jobseekerprofile_phone_and_more'),
        ('core', '0003_job_skills'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='application',
            options={'verbose_name': 'Application', 'verbose_name_plural': 'Applications'},
        ),
        migrations.AlterUniqueTogether(
            name='application',
            unique_together={('job', 'seeker')},
        ),
    ]
