# Generated by Django 5.2.3 on 2025-06-27 08:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0008_delete_seekerfeedback'),
        ('core', '0004_alter_application_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedbackRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.DecimalField(decimal_places=1, help_text='Rating from 1.0 to 5.0', max_digits=3)),
                ('comment', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('feedback_type', models.CharField(choices=[('APPLICATION', 'Application Feedback'), ('PROFILE', 'Profile Feedback')], default='APPLICATION', max_length=20)),
                ('application', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='core.application')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='all_feedbacks', to='authentication.jobseekerprofile')),
                ('recruiter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='given_feedbacks', to='authentication.recruiterprofile')),
            ],
            options={
                'verbose_name': 'Feedback & Rating',
                'verbose_name_plural': 'Feedback & Ratings',
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('application__isnull', False)), fields=('recruiter', 'application'), name='unique_application_feedback')],
            },
        ),
    ]
