from django.urls import path
from .views import (
    JobCreateView,
    JobListView,
    JobDetailView,
    ApplicationCreateView,
    ApplicationListView,
    JobRecommendationView,
    CandidateRecommendationView,
    JobUpdateNextStepView,
    ApplicationNextStepView,
    ApplicationApproveNextStepView,
    ToggleAvailabilityView,
    DashboardStatsView,
    RecruiterDashboardStatsView,
    EmployerJobsView,
    JobApplicantsView,
    ApplicationFeedbackView,
    SeekerFeedbackView,
    ApplicationDetailView,
    ApplicationStatusUpdateView,
    JobInviteApplicantView
)

urlpatterns = [
    path('jobs/', JobListView.as_view(), name='job-list'),
    path('jobs/create/', JobCreateView.as_view(), name='job-create'),
    path('jobs/<int:pk>/', JobDetailView.as_view(), name='job-detail'),
    path('jobs/<int:pk>/update-next-step/', JobUpdateNextStepView.as_view(), name='job-update-next-step'),
    path('jobs/employer/', EmployerJobsView.as_view(), name='employer-jobs'),
    path('applications/', ApplicationListView.as_view(), name='application-list'),
    path('applications/create/', ApplicationCreateView.as_view(), name='application-create'),
    path('jobs/recommended/', JobRecommendationView.as_view(), name='job-recommendation'),
    path('jobs/<int:job_id>/candidates/', CandidateRecommendationView.as_view(), name='candidate-recommendation'),
    path('jobs/<int:job_id>/applicants/', JobApplicantsView.as_view(), name='job-applicants'),
    path('applications/<int:pk>/next-step/', ApplicationNextStepView.as_view(), name='application-next-step'),
    path('applications/<int:pk>/approve-next-step/', ApplicationApproveNextStepView.as_view(), name='application-approve-next-step'),
    path('jobs/<int:job_id>/invite/', JobInviteApplicantView.as_view(), name='job-invite-applicant'),
    path('applications/<int:pk>/status/', ApplicationStatusUpdateView.as_view(), name='application-status-update'),
    path('seeker/toggle-availability/', ToggleAvailabilityView.as_view(), name='toggle-availability'),
    path('dashboard/stats/', DashboardStatsView.as_view(), name='dashboard-stats'),
    path('dashboard/recruiter-stats/', RecruiterDashboardStatsView.as_view(), name='recruiter-dashboard-stats'),
    path('applications/<int:pk>/', ApplicationDetailView.as_view(), name='application-detail'),
    path('applications/<int:pk>/feedback/', ApplicationFeedbackView.as_view(), name='application-feedback'),
    path('seekers/<int:profile_id>/feedback/', SeekerFeedbackView.as_view(), name='seeker-feedback'),
]
