# Generated by Django 5.2.3 on 2025-06-19 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobseekerprofile',
            name='availability_status',
            field=models.CharField(choices=[('AVAILABLE', 'Available'), ('BUSY', 'Busy'), ('NOT_LOOKING', 'Not Looking')], default='AVAILABLE', max_length=20),
        ),
    ]
