# Generated by Django 5.2.3 on 2025-06-19 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_jobseekerprofile_availability_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobseekerprofile',
            name='availability_status',
        ),
        migrations.AddField(
            model_name='jobseekerprofile',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
    ]
