# Generated by Django 5.2.3 on 2025-06-20 02:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_remove_jobseekerprofile_availability_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SeekerFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField()),
                ('comment', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recruiter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='given_feedbacks', to='authentication.recruiterprofile')),
                ('seeker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='authentication.jobseekerprofile')),
            ],
            options={
                'unique_together': {('seeker', 'recruiter')},
            },
        ),
    ]
