# Generated by Django 5.2.3 on 2025-06-25 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_jobseekerprofile_linkedin_jobseekerprofile_phone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recruiterprofile',
            name='industry',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
